### ISSUE TITLE
USER STORY: View Products

### ISSUE THREAD

**Issue by TMartin88** [TMartin88/ski_shop#1]
As a **shopper**, I want **to be able to view a list of products**, so that **so that I can review them with a view to purchase**.

## Acceptance Criteria
- [x] **Categories**
- [x] **Products**
- [x] **Images**

## Tasks
- [x] Setup Category model
- [x] Setup Product Model
- [x] Setup Fixtures
- [x] Populate Fixtures
- [x] Style Product Page
