### ISSUE TITLE
USER STORY: Shopper Profile

### ISSUE THREAD

**Issue by TMartin88** [TMartin88/ski_shop#13]
As a **shopper**, I want **to be able to create a profile**, so that **my shopping experience can be a more personal experience**.

## Acceptance Criteria
- [x] **Register as User**
- [x] **Login as User**
- [x] **View Cart**

## Tasks
- [x] Create Profile App
- [x] Model
- [x] Templates
- [x] Views
